import cv2
import numpy as np
import subprocess
import tempfile
import shutil
import re
from pathlib import Path
from PIL import Image


# ============================================================
# CONFIGURATION
# ============================================================

BASE = Path(r"F:\protrace\potrace-1.16.win64")
POTRACE = BASE / "potrace.exe"

INPUT = Path(r"F:\protrace\color.jpg")
OUTPUT = Path(r"F:\protrace\color-vector.svg")

# Mean-shift parameters
SPATIAL_RADIUS = 10
COLOR_RADIUS = 20

# Ignore extremely tiny regions
MIN_REGION_AREA = 100

# Maximum number of regions to vectorize.
# Set to None for no limit.
MAX_REGIONS = 150


# ============================================================
# UTILITIES
# ============================================================

def rgb_to_hex(rgb):
    r, g, b = [int(x) for x in rgb]
    return f"#{r:02x}{g:02x}{b:02x}"


def run_potrace(mask_path, svg_path):
    cmd = [
        str(POTRACE),
        str(mask_path),
        "-b",
        "svg",
        "--group",
        "-o",
        str(svg_path),
    ]

    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def extract_paths(svg_text):
    """
    Extract path elements generated by Potrace.

    We deliberately keep the path geometry and discard Potrace's
    outer SVG wrapper because we will assemble the final SVG ourselves.
    """

    paths = re.findall(r"<path\b[^>]*>", svg_text)

    cleaned = []

    for path in paths:
        if "d=" not in path:
            continue

        # Remove Potrace's fill/stroke attributes.
        path = re.sub(r'\s+fill="[^"]*"', "", path)
        path = re.sub(r'\s+stroke="[^"]*"', "", path)

        cleaned.append(path)

    return cleaned


# ============================================================
# MAIN
# ============================================================

def main():

    if not INPUT.exists():
        raise FileNotFoundError(INPUT)

    if not POTRACE.exists():
        raise FileNotFoundError(POTRACE)

    print("=" * 60)
    print("COLOR VECTORIZE")
    print("=" * 60)

    # --------------------------------------------------------
    # Load original image
    # --------------------------------------------------------

    original = cv2.imread(str(INPUT), cv2.IMREAD_COLOR)

    if original is None:
        raise RuntimeError("Could not load input image.")

    height, width = original.shape[:2]

    print(f"Input: {INPUT}")
    print(f"Size:  {width} x {height}")

    # --------------------------------------------------------
    # Mean-shift segmentation
    # --------------------------------------------------------

    print()
    print("Running mean-shift segmentation...")

    segmented = cv2.pyrMeanShiftFiltering(
        original,
        SPATIAL_RADIUS,
        COLOR_RADIUS,
    )

    cv2.imwrite(
        str(INPUT.parent / "color-segmented.jpg"),
        segmented
    )

    # --------------------------------------------------------
    # Convert segmented image to RGB
    # --------------------------------------------------------

    segmented_rgb = cv2.cvtColor(
        segmented,
        cv2.COLOR_BGR2RGB
    )

    # --------------------------------------------------------
    # Find unique color regions
    # --------------------------------------------------------

    print("Finding color regions...")

    pixels = segmented_rgb.reshape(-1, 3)

    colors, inverse = np.unique(
        pixels,
        axis=0,
        return_inverse=True
    )

    labels = inverse.reshape(height, width)

    print(f"Unique segmented colors: {len(colors)}")

    # --------------------------------------------------------
    # Temporary working directory
    # --------------------------------------------------------

    temp_dir = Path(
        tempfile.mkdtemp(prefix="protrace_")
    )

    all_paths = []

    region_info = []

    try:

        # ----------------------------------------------------
        # Process each color
        # ----------------------------------------------------

        for color_index, color in enumerate(colors):

            color_mask = (labels == color_index).astype(np.uint8)

            area = int(color_mask.sum())

            if area < MIN_REGION_AREA:
                continue

            # ------------------------------------------------
            # Find connected components within this color
            # ------------------------------------------------

            count, component_labels, stats, centroids = \
                cv2.connectedComponentsWithStats(
                    color_mask,
                    connectivity=8
                )

            for component_id in range(1, count):

                component_area = int(
                    stats[component_id, cv2.CC_STAT_AREA]
                )

                if component_area < MIN_REGION_AREA:
                    continue

                component_mask = (
                    component_labels == component_id
                ).astype(np.uint8) * 255

                region_info.append(
                    (
                        component_area,
                        color.copy(),
                        component_mask
                    )
                )

        # ----------------------------------------------------
        # Largest regions first
        # ----------------------------------------------------

        region_info.sort(
            key=lambda x: x[0],
            reverse=True
        )

        if MAX_REGIONS is not None:
            region_info = region_info[:MAX_REGIONS]

        print(
            f"Regions selected for vectorization: "
            f"{len(region_info)}"
        )

        # ----------------------------------------------------
        # Save region preview
        # ----------------------------------------------------

        preview = np.zeros_like(original)

        for area, color, mask in region_info:

            bgr = (
                int(color[2]),
                int(color[1]),
                int(color[0])
            )

            preview[mask > 0] = bgr

        cv2.imwrite(
            str(INPUT.parent / "color-regions-preview.png"),
            preview
        )

        # ----------------------------------------------------
        # Vectorize every region
        # ----------------------------------------------------

        for index, (area, color, mask) in enumerate(region_info):

            mask_path = temp_dir / f"region_{index:04d}.pbm"
            svg_path = temp_dir / f"region_{index:04d}.svg"

            # Pillow writes a valid PBM for Potrace.
	potrace_mask = 255 - mask

            pil_mask = Image.fromarray(mask).convert("1")
            pil_mask.save(mask_path)

            try:
                run_potrace(mask_path, svg_path)

                svg_text = svg_path.read_text(
                    encoding="utf-8"
                )

                paths = extract_paths(svg_text)

                if not paths:
                    continue

                fill = rgb_to_hex(color)

                for path in paths:

                    # Insert the region's actual color.
                    path = re.sub(
                        r"<path\b",
                        f'<path fill="{fill}"',
                        path,
                        count=1
                    )

                    all_paths.append(path)

            except subprocess.CalledProcessError as e:

                print(
                    f"Potrace failed on region {index}: "
                    f"{e}"
                )

        # ----------------------------------------------------
        # Build final SVG
        # ----------------------------------------------------

        print()
        print("Assembling SVG...")

        svg = []

        svg.append(
            '<?xml version="1.0" encoding="UTF-8"?>'
        )

        svg.append(
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'width="{width}" height="{height}" '
            f'viewBox="0 0 {width} {height}">'
        )

        svg.append(
            '<g shape-rendering="geometricPrecision">'
        )

        svg.extend(all_paths)

        svg.append("</g>")
        svg.append("</svg>")

        OUTPUT.write_text(
            "\n".join(svg),
            encoding="utf-8"
        )

        print()
        print("=" * 60)
        print("DONE")
        print("=" * 60)

        print(f"Output: {OUTPUT}")
        print(f"Paths:  {len(all_paths)}")
        print(
            f"Preview: "
            f"{INPUT.parent / 'color-regions-preview.png'}"
        )
        print(
            f"Segmentation: "
            f"{INPUT.parent / 'color-segmented.jpg'}"
        )

    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


if __name__ == "__main__":
    main()