[Rainmeter]
Update=1000

[MeasureDay]
Measure=Time
Format=%A

[MeasureDate]
Measure=Time
Format=%B %d, %Y


[MeterBackground]
Meter=Image
SolidColor=0,0,0,1
X=0
Y=0
W=600
H=100

[MeterDay]
Meter=String
MeasureName=MeasureDay

X=300
Y=0
FontSize=30
FontWeight=700
FontColor=255,255,255,255
FontFace=Ethnocentric Regular
StringAlign=Center
StringCase=Upper
AntiAlias=1

[MeterDate]
Meter=String
MeasureName=MeasureDate
X=300
Y=-5R
FontSize=16
FontWeight=400
FontColor=255,255,255,180
FontFace=Exo2 Medium
StringAlign=Center
StringCase=Upper
AntiAlias=1

; This is a updated version of Myhome rainmeter widget, it solves the wedget position shifting based on the day problem!
